baseurl = "http://blog.sebastinsanty.com"
languageCode = "en"
title = "In a Code Reverie"
theme = "Hucore"
copyright = "&copy; 2017 | <a href=\"http://sebastinsanty.com\" target=\"_blank\">Sebastin Santy</a> | <a href=\"https://github.com/mgjohansen/hucore.git\" target=\"_blank\">Hucore theme</a> & <a href=\"http://gohugo.io\" target=\"_blank\">Hugo</a> ♥"
disqusShortname = "sebastins-blog"
googleAnalytics = "UA-99569818-1"

[taxonomies]
tag = "tags"
category = "categories"

[params]
description = "Majoring in Electronics at BITS Pilani, Goa. Open-Source Enthusiast and an Avid Programmer"
keywords = ["mozilla", "sebastin santy", "bits pilani"]
author = "Sebastin Santy"
sharingicons = true

[params.highlight]
style = "github"
languages = ["python", "javascript"]

[[params.social]]
url = "http://sebastinsanty.com"
fa_icon = "fa-globe"

[[params.social]]
url = "https://github.com/SebastinSanty"
fa_icon = "fa-github"

[[params.social]]
url = "https://twitter.com/sebastinsanty"
fa_icon = "fa-twitter"

[[params.social]]
url = "https://linkedin.com/in/sebastinsanty"
fa_icon = "fa-linkedin-square"

[[params.social]]
url = "/index.xml"
fa_icon = "fa-rss"

[[params.socialshare]]
url = "https://linkedin.com/in/sebastinsanty"
fa_icon = "fa-linkedin-square"
